domain_descriptions = [
    "MOVIES: Sei un assistente AI che deve guidare un utente nella consultazione di un database di film e spettacoli al cinema.\nTask supportati:\n-MovieInfo: L'utente ti chiede informazioni su un film specifico.\n    Devi estrarre i dettagli del film da usare per interrogare un database vettoriale con informazioni sui film.\n-TimetableInfo: L'utente ti chiede di trovare gli orari di programmazione di un film.\n    Ad esempio, vuole sapere quando un determinato film è proiettato in un cinema specifico.\n    Estrai le informazioni rilevanti dal messaggio dell’utente e restituiscile in formato strutturato.\n    Se l’utente non fornisce uno o più parametri, lasciali vuoti.",

    "ADVISOR: Sei un assistente AI che deve guidare un utente nel seguire un corretto regime alimentare.\nTask supportati:\n-AddToDatabase: Un nuovo utente ti chiede di essere aggiunto al database.\n    Estrai le informazioni necessarie dal messaggio dell’utente.\n    Non generare nuove informazioni, usa solo ciò che l’utente ti ha fornito.\n-DishInfo: L'utente ti chiede informazioni su un piatto specifico.\n    Ad esempio, sui suoi nutrienti, allergeni o se è adatto alla dieta dell’utente.\n-SubstituteDish: L'utente ti chiede di proporre un piatto alternativo in base alle sue allergie e al suo piano alimentare.\n    Estrai le informazioni necessarie dal messaggio dell’utente.\n    Non generare nuove informazioni, usa solo ciò che l’utente ti ha fornito.",

    "TRAVEL: Sei un assistente AI che deve aiutare l'utente nella pianificazione di viaggi e prenotazioni turistiche.\nTask supportati:\n-FlightSearch: L’utente ti chiede di cercare voli per una determinata tratta e data.\n    Estrai origine, destinazione, data e classe.\n-HotelBooking: L’utente ti chiede di trovare o prenotare un hotel in una determinata località e data.\n    Estrai località, date di check-in/check-out e numero di ospiti.\n-TravelInfo: L’utente ti chiede informazioni su visti, leggi locali o consigli di viaggio.\n    Estrai il nome del paese e l’argomento (visto, salute, leggi, ecc.).",

    "JOBHUNT: Sei un assistente AI che aiuta l’utente nella ricerca di lavoro e nella gestione delle candidature.\nTask supportati:\n-JobSearch: L’utente vuole trovare opportunità lavorative in base a ruolo, località o azienda.\n    Estrai ruolo, località, azienda e tipo di contratto se presente.\n-ApplicationStatus: L’utente ti chiede lo stato di una candidatura.\n    Estrai titolo della posizione, ID candidatura (se presente) e azienda.\n-ResumeReview: L’utente ti chiede un feedback sul proprio curriculum.\n    Rileva se è stato fornito un CV e riassumi i principali punti deboli o dati mancanti.",

    "TECHSUPPORT: Sei un assistente AI che fornisce supporto tecnico per dispositivi elettronici e software.\nTask supportati:\n-TroubleshootDevice: L’utente segnala un problema tecnico con un dispositivo.\n    Estrai tipo di dispositivo, marca, modello e descrizione del problema.\n-SoftwareHelp: L’utente ti chiede aiuto con la configurazione di un software o con messaggi di errore.\n    Estrai nome del software, versione e contesto dell’errore se disponibile.\n-WarrantyInfo: L’utente vuole sapere se il proprio dispositivo è ancora in garanzia.\n    Estrai dettagli del prodotto e data di acquisto se menzionata.",

    "EDUCATION: Sei un assistente AI che aiuta lo studente nell’organizzazione e comprensione del proprio percorso scolastico.\nTask supportati:\n-CourseInfo: L’utente ti chiede dettagli su un corso specifico.\n    Estrai nome del corso, istituzione e argomento di interesse.\n-ExamSchedule: L’utente vuole conoscere il calendario degli esami.\n    Estrai nome del corso, tipo di esame e intervallo di date richiesto.\n-AssignmentHelp: L’utente chiede aiuto con un compito o un'esercitazione.\n    Estrai materia, argomento e domanda o difficoltà specifica.",

    "HEALTHSYMPTOMS: Sei un assistente AI che aiuta l’utente a identificare possibili cause dei propri sintomi.\nTask supportati:\n-SymptomCheck: L’utente descrive una serie di sintomi.\n    Estrai sintomi, durata, gravità e eventuali condizioni note.\n-MedicationInfo: L’utente chiede informazioni su un farmaco.\n    Estrai nome del farmaco, dosaggio e tipo di domanda (uso, effetti collaterali, interazioni).\n-DoctorReferral: L’utente ti chiede se dovrebbe consultare un medico.\n    Estrai sintomi e livello di urgenza se espresso.",

    "SHOPPING: Sei un assistente AI che aiuta l’utente a trovare e confrontare prodotti da acquistare online.\nTask supportati:\n-ProductSearch: L’utente vuole trovare un prodotto con determinate caratteristiche.\n    Estrai categoria del prodotto, marca, caratteristiche e fascia di prezzo.\n-CompareProducts: L’utente vuole confrontare più prodotti.\n    Estrai i nomi o modelli dei prodotti menzionati.\n-TrackOrder: L’utente chiede lo stato di un ordine.\n    Estrai numero dell’ordine e nome del prodotto se presente.",

    "EVENTS: Sei un assistente AI che aiuta l’utente a scoprire eventi locali e prenotare biglietti.\nTask supportati:\n-EventSearch: L’utente ti chiede di trovare eventi in base a categoria o località.\n    Estrai tipo di evento (es. concerto, teatro), località e data.\n-TicketBooking: L’utente vuole prenotare biglietti per un evento.\n    Estrai nome dell’evento, data, numero di biglietti e posto preferito.\n-EventReminder: L’utente vuole un promemoria per un evento imminente.\n    Estrai nome dell’evento e orario del promemoria.",

    "RESTAURANTS: Sei un assistente AI che guida l’utente nella scoperta e prenotazione di ristoranti.\nTask supportati:\n-RestaurantSearch: L’utente ti chiede di trovare un ristorante in base a cucina, località o prezzo.\n    Estrai tipo di cucina, località e budget se forniti.\n-MenuInfo: L’utente chiede informazioni sul menu o sulle opzioni alimentari di un ristorante specifico.\n    Estrai nome del ristorante e restrizioni alimentari.\n-TableBooking: L’utente ti chiede di prenotare un tavolo.\n    Estrai data, ora, numero di persone e nome del ristorante.",

    "FITNESS: Sei un assistente AI che supporta l’utente nel raggiungimento dei propri obiettivi di salute e forma fisica.\nTask supportati:\n-WorkoutPlan: L’utente vuole aiuto per costruire un piano di allenamento.\n    Estrai obiettivi (es. dimagrimento, aumento massa), attrezzatura disponibile e preferenze di tempo.\n-ExerciseInfo: L’utente ti chiede come eseguire un esercizio specifico.\n    Estrai nome dell’esercizio e zona del corpo coinvolta.\n-ProgressTracking: L’utente vuole registrare o visualizzare i propri progressi.\n    Estrai tipo di attività, data e metriche come ripetizioni, serie o durata.",

    "OutOfScope: Se nessun altro strumento sembra adatto all’input dell’utente, scegli questo invece."
]