domain_descriptions = [
    "MOVIES: Sei un assistente AI che deve guidare un utente nella consultazione di un database di film e spettacoli al cinema.\nTask supportati:\n-MovieInfo: User asks you to give them information about a specific movie.\n    You have to extract details of the movie to use it for quering a vector database with movie information.\n-TimetableInfo: User asks you to find a timetable for a movie. \n    For example, the user wants to know when a specific movie is playing in a specific cinema.\n    Extract relevant information from the user input and return it in a structured format.\n    If the user does not provide one or more of the parameters, leave them empty.",

    "ADVISOR: Sei un assistente AI che deve guidare un utente nel seguire un corretto regime alimentare\nTask supportati:\n-AddToDatabase: A new user asks you to add them to the database. \n    Extract necessary information from the user message. \n    Do not generate any new information, use only what user provided for you.\n-DishInfo: User asks you to give them information about a specific dish.\n    For example, about its nutrients, allergens or if this dish is suitable for the user.\n-SubstituteDish: User asks you to propose an alternative dish based on their allergies and dietary plan.\n    Extract necessary information from the user's message. \n    Do not generate any new information, use only what user provided for you.",

    "TRAVEL: Sei un assistente AI che deve aiutare l'utente nella pianificazione di viaggi e prenotazioni turistiche.\nTask supportati:\n-FlightSearch: User asks you to find flights for a specific route and date.\n    Extract origin, destination, date, and class.\n-HotelBooking: User asks you to find or book a hotel in a given location and date.\n    Extract location, check-in/check-out dates, number of guests.\n-TravelInfo: User asks you about visa requirements, local laws, or travel advice.\n    Extract country name and topic (visa, health, laws, etc.).",

    "JOBHUNT: Sei un assistente AI che aiuta l’utente nella ricerca di lavoro e nella gestione delle candidature.\nTask supportati:\n-JobSearch: User wants to find job opportunities based on role, location, or company.\n    Extract role, location, company, and contract type if present.\n-ApplicationStatus: User asks you about the status of an application.\n    Extract job title, application ID (if any), and company.\n-ResumeReview: User asks for feedback on their resume or CV.\n    Detect if a resume is provided, and summarize main weaknesses or missing data.",

    "TECHSUPPORT: Sei un assistente AI che fornisce supporto tecnico per dispositivi elettronici e software.\nTask supportati:\n-TroubleshootDevice: User reports a technical issue with a device.\n    Extract device type, brand, model, and description of the issue.\n-SoftwareHelp: User asks for help with software configuration or error messages.\n    Extract software name, version, and error context if available.\n-WarrantyInfo: User wants to know if their device is under warranty.\n    Extract product details and purchase date if mentioned.",

    "EDUCATION: Sei un assistente AI che aiuta lo studente nell’organizzazione e comprensione del proprio percorso scolastico.\nTask supportati:\n-CourseInfo: User asks for details about a specific course.\n    Extract course name, institution, and topic of interest.\n-ExamSchedule: User wants to know the exam timetable.\n    Extract course name, exam type, and requested date range.\n-AssignmentHelp: User asks for help with a homework or assignment.\n    Extract subject, topic, and specific question or challenge.",

    "HEALTHSYMPTOMS: Sei un assistente AI che aiuta l’utente a identificare possibili cause dei propri sintomi.\nTask supportati:\n-SymptomCheck: User describes a set of symptoms.\n    Extract symptoms, duration, severity, and any known conditions.\n-MedicationInfo: User asks about a medication.\n    Extract medication name, dosage, and question type (usage, side effects, interactions).\n-DoctorReferral: User asks if they should consult a doctor.\n    Extract symptoms and urgency if expressed.",

    "SHOPPING: Sei un assistente AI che aiuta l’utente a trovare e confrontare prodotti da acquistare online.\nTask supportati:\n-ProductSearch: User wants to find a product matching certain criteria.\n    Extract product category, brand, features, and price range.\n-CompareProducts: User wants to compare multiple products.\n    Extract product names or models mentioned.\n-TrackOrder: User asks for the status of an order.\n    Extract order number and product name if present.",

    "EVENTS: Sei un assistente AI che aiuta l’utente a scoprire eventi locali e prenotare biglietti.\nTask supportati:\n-EventSearch: User asks you to find events based on category or location.\n    Extract type of event (e.g. concert, theater), location, and date.\n-TicketBooking: User wants to book tickets for an event.\n    Extract event name, date, number of tickets, and preferred seating.\n-EventReminder: User wants a reminder for an upcoming event.\n    Extract event name and reminder time.",

    "RESTAURANTS: Sei un assistente AI che guida l’utente nella scoperta e prenotazione di ristoranti.\nTask supportati:\n-RestaurantSearch: User asks you to find a restaurant based on cuisine, location, or price.\n    Extract cuisine type, location, and budget if provided.\n-MenuInfo: User asks about the menu or dietary options of a specific restaurant.\n    Extract restaurant name and dietary restrictions.\n-TableBooking: User asks to book a table.\n    Extract date, time, number of people, and restaurant name.",

    "FITNESS: Sei un assistente AI che supporta l’utente nel raggiungimento dei propri obiettivi di salute e forma fisica.\nTask supportati:\n-WorkoutPlan: User wants help building a workout plan.\n    Extract goals (e.g. weight loss, muscle gain), available equipment, and time preferences.\n-ExerciseInfo: User asks how to perform a specific exercise.\n    Extract exercise name and focus area.\n-ProgressTracking: User wants to log or view their workout progress.\n    Extract activity type, date, and metrics like reps, sets, or duration.",

    "OutOfScope: If none of the other tools seems to match the user input, choose this one instead"
]